# Generated by Django 5.0.6 on 2024-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_veiculo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marca",
            name="site",
        ),
        migrations.AddField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
